### ISSUE TITLE
ModuleNotFoundError: No module named 'ConfigParser'

### ISSUE THREAD

**Issue by kamal2222ahmed** [saymedia/seosuite#4]
$ pip install -r requirements.txt
Collecting MySQL-python==1.2.5 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/a5/e9/51b544da85a36a68debe7a7091f068d802fc515a3a202652828c73453cad/MySQL-python-1.2.5.zip (108kB)
    100% |████████████████████████████████| 112kB 2.8MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/jr/kc1rdmj10jb4p1hrw77zttq00000gn/T/pip-install-90l7_ndp/MySQL-python/setup.py", line 13, in <module>
        from setup_posix import get_config
      File "/private/var/folders/jr/kc1rdmj10jb4p1hrw77zttq00000gn/T/pip-install-90l7_ndp/MySQL-python/setup_posix.py", line 2, in <module>
        from ConfigParser import SafeConfigParser
    ModuleNotFoundError: No module named 'ConfigParser'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/jr/kc1rdmj10jb4p1hrw77zttq00000gn/T/pip-install-90l7_ndp/MySQL-python/

**Comment by davidminor** [comment]
Hi, thank you for this report but as the README says this project is no longer maintained. I'm going to go ahead and archive it to make that clearer. Sorry about that!
